### ISSUE TITLE
<hi rend="i"> tags in illustration description and copy information (probably all xml)

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#282] opened 2016-07-27 21:06 UTC
it's missing text within tags within the illustration description tags.

for example,
`<hi rend="i">A Midsummer Night's Dream</hi>`
is not showing in the illustration description for http://localhost:8002/blake/copy/s-los.b?descId=s-los.b.illbk.05

**Comment by queryluke** [comment] 2016-08-03 15:56
duplicate of #295

**Closed by queryluke** 2016-08-03 15:56 UTC
Labels: duplicate
