### ISSUE TITLE
electronic edition information for copies needs to be put under its own tab and rendered properly

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#228] opened 2016-05-20 13:55 UTC
\<header\> in BADs

with an index to the BADs for that work so that a user can see the XML

see http://www.blakearchive.org/exist/blake/archive/filedesc.xq?copyid=mhh.e

**Comment by queryluke** [comment] 2016-07-18 22:05
So this will not be possible with the current XML. For example, here is what the json looks like for the principal tag:

```
principal:Object
  #text:"University of↵Rochester;↵University of California, Riverside;↵and↵, University of North Carolina at↵Chapel Hill"
  name:Array[3]
    0:Object
      #text:"Morris Eaves,"
    1:Object
      #text:"Robert Essick,"
    2:Object
      #text:"Joseph Viscomi"
```

I can use js to interject the names, but that's not ideal. And I'd be willing to do it, but then look at the respstmt:
```
respstmt:Object
  #text:"and"
  name:Array[4]
    0:Object
      #text:"David Cosca"
    1:Object
      #text:"Robert Bingler"
    2:Object
      #text:"Matthew↵Kirschenbaum"
    3:Object
      #text:"Greg↵Murray"
  resp:Array[3]
    0:Object
      #text:"Programmer/Analysts:"
    1:Object
      #text:"Project Manager:"
    2:Object
      #text:"Project Assistant:"
````

I've got no way of associating the correct names to the correct titles. Trying to solve this from the python import scripts won't be possible. The problem is the XML is structure like HTML, e.g.:

```
<principal>
<resp>Editors:</resp>
<name>Morris Eaves,</name>
University of Rochester;
<name>Robert Essick,</name>
University of California, Riverside; and
<name>Joseph Viscomi</name>
, University of North Carolina at Chapel Hill
</principal>
```

Those universities should get their own tags, and punctuation should not be part of it:
```
<editors>
  <person>
    <name>Morris Eaves</name>
    <university>University of Rochester</university>
  </person>
  <person>
    <name>Robert Essick</name>
    <university>University of California, Riverside</university>
  </person>
  <person>
    <name>Joseph Viscomi</name>
    <university>University of North Carolina at Chapel Hill</university>
  </person>
</editors>
```

For now, we'll have to link to the xml file and put this in a future release. The only quick fix I can think off: @nathan-rice, would it be possible to add the rendered html to the blake_copy/blake_object? Like we do with the text transcriptions

**Comment by nathan-rice** [comment] 2016-07-19 14:30
I strongly agree about the structure of the XML documents needing revision.  The XML is frequently treated like a traditional document, when it is really structured hierarchical data.

I can create a XML/HTML copy of the header field and add that to the model.  The main question is, does it need to be piped through some sort of transform (such as the XSLTs) to be useful?  

I personally think surfacing the XML to users is a bad idea, and if it is done it certainly shouldn't be via something as highly visible as another tab in the menu; it should be via an out of the way button/link.

**Comment by queryluke** [comment] 2016-07-19 15:33
Yes, it would need to be piped through the xslts to be useful. I think we should let @foxm and @joeafletch bring these concerns to the stakeholders before implement anything.

**Comment by foxm** [comment] 2016-07-19 18:41
We'll have to render the electronic edition info like we do the transcriptions. I've attached the xsl for doing so. And the links to the BADs should go under the tab along with the info.
[source.xsl.zip](https://github.com/blakearchive/archive/files/372186/source.xsl.zip)

**Comment by nathan-rice** [comment] 2016-07-19 19:37
I've added source_html (transformed) and bad_xml fields to the BlakeCopy model, and updated the database to reflect this change.

**Comment by queryluke** [comment] 2016-07-19 21:32
source_html seems to only return the following:
```
<div xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:exist="http://exist.sourceforge.net/NS/exist" xmlns:fn="http://www.w3.org/2005/02/xpath-functions"><p><script language="JavaScript"> datestamp( ); </script></p></div>
```

Additionally, and why I wanted to hold off on this is that we have to deal with virtual groups as well. For a virtual group, the source data comes from a completely separate file in data/groups/, which I guess can be attached to the virtual copy...

But before going down that rabbit hole, I'd like to get the priority of this feature, keeping in mind that we can put a link to the xml (which has all of this info) on the copy info tab. Then we can always circle back around to this in a future release.

**Comment by foxm** [comment] 2016-07-21 13:25
i had a conversation with the editors about this, explaining to them why it's not straightforward to implement. without going into the details, i'll just say they have their reasons for rendering all of the electronic edition info, including the link to the BAD, so it looks like we'll have to do it. but we can wait to do it for the production release

**Comment by queryluke** [comment] 2016-07-25 13:24
@nathan-rice, did you see my comment about source_html? Can you take a look?

In addition, the virtual groups have their electronic information in a separate xml file: ```data/groups/<groupname>.xml```

**Comment by nathan-rice** [comment] 2016-07-25 16:15
This should be fixed now.

I've also incorporated virtual group source xml file info.

**Comment by foxm** [comment] 2016-07-25 22:01
getting an error:

DEBUG [9d2dba30] Command: cd ~/Sites/blake/archive/blakearchive/; python import.py '../data/works/*.xml' '../data/info/*.xml'; python solrimport.py; python homepageimport.py;
DEBUG [9d2dba30] 	usage: import.py [-h] data_folder
DEBUG [9d2dba30] 	import.py: error: unrecognized arguments: ../data/info/*.xml

**Comment by nathan-rice** [comment] 2016-07-25 22:04
Yeah, I modified the import script to only take one parameter, the root data directory.  I emailed Luke to inform him of this; I could have done the same for you, except you automatically delete my emails.

**Comment by queryluke** [comment] 2016-07-25 22:28
Sorry @nathan-rice, I miscommunicated what needs to get transformed.

It's not the copy source but the copy header. I.e., whatever is getting parsed into the header attribute on the copy model. Is that going to be possible?

@foxm the cap scripts should be updated. If they don't work, instead of running them, you can cd into /blakearchive and run ```python import.py '../data'

**Comment by foxm** [comment] 2016-07-25 22:28
to remove error, edited db.rake to have import.py take one parameter (../data)

**Comment by nathan-rice** [comment] 2016-07-25 22:43
It was the name of the XSLT that confused me.  Switching the transform to take the header, and renaming the relevant model fields are both trivial.

**Comment by foxm** [comment] 2016-07-25 22:59
thanks, luke @queryluke

**Comment by nathan-rice** [comment] 2016-07-26 14:25
The transformed header is now present on the data model as header_html.

**Comment by queryluke** [comment] 2016-07-26 20:36
did you push those changes?

**Comment by nathan-rice** [comment] 2016-07-26 20:37
Apparently not.  Fixed.

**Comment by foxm** [comment] 2016-07-27 01:38
@queryluke great! the display is inconsistent, but that's because of the inconsistency of the BADs. i can get an assistant to make them as consistent as possible. but the virtual groups and letters' eeinfo isn't showing. open another issue for those?

**Comment by queryluke** [comment] 2016-07-27 01:48
No I was just looking at that. We'll need some clarification.

On the current site, it looks like the information from the group file is display.

See that 
http://www.blakearchive.org/exist/blake/archive/copyinfo.xq?mode=eei_vgroup&group=allegropenseroso
Corresponds to ```/groups/allegropenseroso.xml```

Then there is a list of BADs for each object in the virtual group, linking to the xml. But each bad in the group also has it's own header information.

So the question is: do we continue with the current convention, i.e. display the contents of ```group/...xml``` and provide links to each bad? Or should we display the header information for each object in that group. Note that on the new site, for the "Object Information" tab, we display the info for each individual object. In other words, the contents of the eeInfo tab would change based on the object being viewed.

**Comment by foxm** [comment] 2016-07-27 01:52
we should continue with how it's currently done. the eeinfo is for the work or the group, not for individual objects. we can clarify that in the tab label or in the title for the tab

**Comment by queryluke** [comment] 2016-07-27 15:48
@nathan-rice, is it possible to have the contents from ```data/group/<bad_id>.xml``` transformed and stored in the header_html attribute for virtual copies? One problem with these files is they don't contain ```<header>``` tags. @foxm, can we add those tags?

**Comment by foxm** [comment] 2016-07-27 17:05
yes, we can, although, i think the eeinfo comes from the filedesc tag, which is common to the copies and the groups

**Comment by queryluke** [comment] 2016-07-27 18:30
Thanks, I've updated my comment to reflect this

**Comment by queryluke** [comment] 2016-08-01 13:27
@nathan-rice, did you my question above, re: getting header_html for virtual copies

**Comment by nathan-rice** [comment] 2016-08-01 14:18
I just pushed something for this, see if it does what you need.

**Comment by queryluke** [comment] 2016-08-01 14:21
that did it, thanks! I'll finish this feature up today.

**Comment by queryluke** [comment] 2016-08-01 15:30
letters are still wonky, but I'll fix this when I refactor how object_groups are handled.

**Closed** 2016-08-01 15:30 UTC
Labels: enhancement
