### ISSUE TITLE
links to letters from homepage are being malformed

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#375] opened 2016-11-24 03:42 UTC
i haven't looked into this yet, so i'm not sure if it is related to #371. for now i'm making a separate issue for it.

links on the homepage to letters are being malformed. for example:

http://london.lib.unc.edu/blake/copy/ltapril1800.1?descId=lt1april1800.1.ltr.01

it should be:

http://london.lib.unc.edu/blake/copy/letters?descId=lt1april1800.1.ltr.01

**Comment by queryluke** [comment] 2016-11-28 16:16
duplicate of #371

**Closed by queryluke** 2016-11-28 16:16 UTC
Labels: duplicate
