### ISSUE TITLE
error in import on qa

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#382] opened 2016-11-29 19:51 UTC
DEBUG [75c9200b] 	import.py:106: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  logger.debug(err.message)
DEBUG [75c9200b] 	Traceback (most recent call last):
  File "import.py", line 475, in <module>
DEBUG [75c9200b] 	    main()
  File "import.py", line 471, in main
    importer.import_data()
  File "import.py", line 68, in import_data
    self.process_relationships()
  File "import.py", line 113, in process_relationships
    self.process_relationship(entry)
  File "import.py", line 118, in process_relationship
    obj.objects_from_same_matrix.extend(self.objects_for_id_string(entry.same_matrix_ids))
AttributeError: 'NoneType' object has no attribute 'objects_from_same_matrix'
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as wren@london.lib.unc.edu: python exit status: 1
python stdout: import.py:106: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  logger.debug(err.message)
Traceback (most recent call last):
  File "import.py", line 475, in <module>
    main()
  File "import.py", line 471, in main
    importer.import_data()
  File "import.py", line 68, in import_data
    self.process_relationships()
  File "import.py", line 113, in process_relationships
    self.process_relationship(entry)
  File "import.py", line 118, in process_relationship
    obj.objects_from_same_matrix.extend(self.objects_for_id_string(entry.same_matrix_ids))
AttributeError: 'NoneType' object has no attribute 'objects_from_same_matrix'
python stderr: Nothing written

SSHKit::Command::Failed: python exit status: 1
python stdout: import.py:106: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  logger.debug(err.message)
Traceback (most recent call last):
  File "import.py", line 475, in <module>
    main()
  File "import.py", line 471, in main
    importer.import_data()
  File "import.py", line 68, in import_data
    self.process_relationships()
  File "import.py", line 113, in process_relationships
    self.process_relationship(entry)
  File "import.py", line 118, in process_relationship
    obj.objects_from_same_matrix.extend(self.objects_for_id_string(entry.same_matrix_ids))
AttributeError: 'NoneType' object has no attribute 'objects_from_same_matrix'
python stderr: Nothing written

Tasks: TOP => deploy:seed
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as wren@london.lib.unc.edu: python exit status: 1
python stdout: import.py:106: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  logger.debug(err.message)
Traceback (most recent call last):
  File "import.py", line 475, in <module>
    main()
  File "import.py", line 471, in main
    importer.import_data()
  File "import.py", line 68, in import_data
    self.process_relationships()
  File "import.py", line 113, in process_relationships
    self.process_relationship(entry)
  File "import.py", line 118, in process_relationship
    obj.objects_from_same_matrix.extend(self.objects_for_id_string(entry.same_matrix_ids))
AttributeError: 'NoneType' object has no attribute 'objects_from_same_matrix'
python stderr: Nothing written

**Comment by queryluke** [comment] 2016-11-30 14:38
Since the only change in the pipeline has been to data (specifically blake-relations.csv), I'm thinking the issue is there. My interpretation of the error is that ```obj.objects_From_same_matrix``` isn't instantiated. Which might be caused by it not having an entry in blake-relations.csv. Maybe?

@nathan-rice can you offer any insight?

**Comment by nathan-rice** [comment] 2016-11-30 15:13
This is actually a result of this line not returning properly:

`obj = self.object_importer.get(entry.desc_id.lower())`

Offhand, this could either be the result of entry.desc_id not being set, or no bad objects existing with the desc_id specified in the entry.

**Comment by foxm** [comment] 2016-11-30 16:00
can we add a debug print statement to determine what entry in blake-relations.csv is not found in the BADs?

**Comment by queryluke** [comment] 2016-11-30 17:45
I put a `print entry.desc_id.lower()` at the top of that block. The id it printed before failure was *s-inn.z.illbk.04*

**Comment by foxm** [comment] 2016-11-30 18:10
@joeafletch joe, i had a look at the BAD for s-inn. it looks like the desc id for object 4 is mis-entered:

 <desc id="s-inn.z.illbk.4" dbi="s-inn.z.P4-6">

and all of the references to its transcribed lines seem mis-entered, too:

<l n="s-inn.z.illbk.4.03" justify="left" indent="2">The Sun does arise,</l>

they should read s-inn.z.illbk.04..., right?

let me know. i can correct them, or you can directly on github.

**Comment by foxm** [comment] 2016-11-30 18:12
would it be possible to add error checking to the import scripts everywhere without actually adding print statements everywhere?

**Comment by nathan-rice** [comment] 2016-11-30 18:58
Sure, just use the logger included in the import script already.  All you need to do is add `logger.info('your_message')` or `logger.debug('your_message')` wherever you want to be able to capture output.  These can be filtered out without removing them later.

**Comment by foxm** [comment] 2016-11-30 19:04
ok, thanks. i think, really we just need it to always print out the problematic BAD whenever there is an error. is there a way to do that without adding the logger statement all over the place?

**Comment by nathan-rice** [comment] 2016-11-30 20:21
There is already a logger debug statement that gets emitted whenever the process command fails on a given bad document.  Currently, this logging statement only catches errors of the ValueError type; this could be expanded to include any sort of error, and out the offending bad_id along with the error message.  That is about the limit of what can be done without putting logger calls all over the place.

**Comment by nathan-rice** [comment] 2016-11-30 20:57
I've pushed a commit that makes these changes.  The only downside is that now bad processing errors of an unexpected kind will no longer terminate the import process, they're just reported and skipped.

**Comment by joeafletch** [comment] 2016-11-30 21:06
I've just edited and committed the BAD for s-inn.z. @foxm, indeed, the desc id (and line numbers) was mis-entered for object 4. And for objects 5-9. This is something we need to make sure the assistants attend to as they markup and transcribe new works.

**Comment by foxm** [comment] 2016-11-30 23:44
saw this in the log for the latest attempt to import:

 logger.debug("Error processing BAD [%s]: %s" % (matching_file, err.message))

**Comment by foxm** [comment] 2016-12-02 15:19
it looks like the logger debug statement is not rendering the variables. in other words, it looks like the line of code is just getting printed out.

**Comment by queryluke** [comment] 2016-12-09 00:32
going to close this since the logger actually spits out the errors now

**Closed by queryluke** 2016-12-09 00:32 UTC
